version: "3.9"
services:
  nginx:
    image: linuxserver/letsencrypt:version-1.11.0
    environment:
      - URL=claes-work.de
      - SUBDOMAINS=strapi,portfolio,klassentreffen,counter
    volumes:
    - ./vnginx:/config
    ports:
      - "188.68.62.174:80:80"
      - "188.68.62.174:443:443"
    networks:
      - claes-work



networks:
  claes-work:
    external: true
